### PR TITLE
Added portuguese translation to solve issue #6

### PR DESCRIPTION
**Pull request by ferracioli**
This pull request adds the Portuguese - Brazil language in the pokédex. The updates include:
- Language dropdown selector instead of switch
- Inclusion of spanish language in the portuguese descriptions, since the Pokédex API does not have official portuguese translation
- Possibility of adding a fourth language by including it in the dictionaries and and ternaries available in the code
image

Final consideration:
- In some parts of the code, I couldn't add a dictionary / switch case structure, so they are built with nested ternaries inside the Angular interpolations
image

### CODE REVIEW

**Comment by ferracioli** [comment]
Oh I didn't noticed it, probably happened due to the lack of official Brazilian entry in the API. Can I adjust the code during the pull request review? This is my first experience with changes during pull requests, so I don't know how to proceed.

**Comment by mariokreitz** [comment]
> Oh I didn't noticed it, probably happened due to the lack of official Brazilian entry in the API. Can I adjust the code during the pull request review? This is my first experience with changes during pull requests, so I don't know how to proceed.

yes you can still commit and push and they will automaticly get present in this PR as far as i know

**Comment by ferracioli** [comment]
Great! I will fix it and commit after my work, thanks :)

**Comment by ferracioli** [comment]
Hey, how is it going?
I fixed the problem in the items list! I discovered that to the spanish translation, the API seems to send first the items description of Pokémon X/Y, and I think the entries for these texts are misplaced with other items(i.e., for the Oran Berry, the text matches Hondew Berry. Since it seems to be a problem with the API texts, I kept this way. Here is a print showing a faulty Pokédex entry:
image
The strange is that for other languages, this Pokédex entry works fine. We keep this way? Other solution would be change the portuguese items text to the english one.

Adding a new content in this update, I also managed to add translations to the hover texts, and since I don't know German, I kept the original text in english. Can you translate it if possible? It is in `pokemon-popup.component.ts`
image

**Review by mariokreitz — APPROVED** [review]

**Comment by mariokreitz** [comment]
> Hey, how is it going? I fixed the problem in the items list! I discovered that to the spanish translation, the API seems to send first the items description of Pokémon X/Y, and I think the entries for these texts are misplaced with other items(i.e., for the Oran Berry, the text matches Hondew Berry. Since it seems to be a problem with the API texts, I kept this way. Here is a print showing a faulty Pokédex entry: image The strange is that for other languages, this Pokédex entry works fine. We keep this way? Other solution would be change the portuguese items text to the english one instead of spanish, since the english entries work fine.
> 
> Adding a new content in this update, I also managed to add translations to the hover texts in the card buttons, and since I don't know German, I kept the original text in english. Can you translate it if possible? It is in `pokemon-popup.component.ts` image

Im doing good on my new project =) thanks
Well yeah, i faced some problems with this API too. But as it is right now, it`s good! I will keep this way. It is my first angular project and with an API like this. I will definitly put this in my portfolio :D thanks alot!

**Comment by ferracioli** [comment]
Great, UR welcome :v
Got it, so let's keep the spanish requests this way, is fine by me as well!
Since is your first project, you are doing great! The code is well structured and easy to understand! Thanks for allowing my participation here with the translation :D

**Pull request merged**
